export const unsuccessfulOrderStyles = {
  container: "bg-white rounded-xl border border-gray-200 overflow-hidden shadow-sm mb-6 flex flex-col md:flex-row",
  leftColumn: "md:w-1/4 p-5 bg-gray-50 border-b md:border-b-0 md:border-r border-gray-200 flex justify-between",
  orderIdLabel: "text-xs text-gray-500 font-medium uppercase tracking-wider block",
  orderIdValue: "text-gray-900 font-semibold",
  statusLabel: "text-xs text-gray-500 font-medium uppercase tracking-wider block flex justify-center mb-2",
  statusBadge: "px-3 py-2 rounded-full text-xs font-semibold",
  statusPending: "bg-yellow-100 text-yellow-800",
  statusCancelled: "bg-orange-100 text-orange-800",
  statusFailed: "bg-red-100 text-red-800",
  statusDefault: "bg-gray-100 text-gray-800",
  rightColumn: "md:w-3/4 px-5 py-4",
  itemsSection: "mb-4",
  itemsLabel: "text-xs text-gray-500 font-medium uppercase tracking-wider block mb-2",
  itemsList: "space-y-2",
  itemRow: "flex justify-between text-sm py-1 border-b border-gray-50 last:border-0",
  itemTitle: "text-gray-700",
  itemPrice: "font-medium text-gray-900",
  totalSection: "border-t pt-2 border-gray-200 flex justify-between items-center",
  totalLabel: "font-semibold text-gray-900 tracking-wide uppercase text-sm",
  totalValue: "font-semibold text-gray-900 tracking-wide uppercase text-md",
};
