export const ordersListStyles = {
  orderCard: "overflow-hidden mt-2",
  sectionContainer: "space-y-6",
  section: "mb-6",
  sectionTitle: "text-md font-semibold text-black tracking-tight flex justify-left items-center mb-3",
  itemListReg: "divide-y divide-indigo-100/50 border border-indigo-200 rounded-xl overflow-hidden bg-indigo-50/50 shadow-sm",
  itemListShirt: "divide-y divide-[#ffd4b3] border border-[#ffd4b3] rounded-xl overflow-hidden bg-[#f1e8e194] shadow-sm",
  itemRowReg: "p-4 flex justify-between items-start hover:bg-indigo-100/30 transition-colors",
  iconWrapperReg: "flex-shrink-0 mt-0.5 mr-3 text-indigo-500",
  itemRowShirt: "p-4 flex justify-between items-start hover:bg-[#f1e8e194] transition-colors",
  iconWrapperShirt: "flex-shrink-0 mt-0.5 mr-3 text-[#B45309]",
  itemContent: "flex items-start text-md",
  itemTitleContainer: "flex flex-col ml-1",
  itemTitle: "font-medium text-gray-900",
  itemDetailsList: "mt-2 flex flex-col space-y-1 text-sm text-gray-600",
  itemPrice: "font-medium text-gray-900 shrink-0 ml-4 text-sm",
};
