export const navbarStyles = {
  nav: [
    "fixed",
    "top-0",
    "left-0",
    "right-0",
    "z-40",
    "flex",
    "items-center",
    "justify-between",
    "px-6",
    "sm:px-10",
    "lg:px-16",
    "py-4",
    "sm:py-6",
    "bg-white/5",
    "backdrop-blur-sm",
    "shadow-sm",
  ].join(" "),

  logo: [
    "text-[18px]",
    "sm:text-[20px]",
    "font-medium",
    "text-[#1a1a1a]",
    "leading-tight",
    "hover:text-black",
    "transition-colors",
    "duration-200",
    "border",
    "border-black/10",
    "rounded-lg",
    "px-3",
    "py-1.5",
  ].join(" "),

  right: "flex items-center justify-end",

  spacer: "h-[72px] sm:h-[88px] w-full",

  divider: [
    "absolute",
    "left-0",
    "right-0",
    "bottom-0",
    "h-px",
    "bg-black/10",
    "origin-left",
    "transition-[opacity,filter]",
    "duration-300",
    "ease-out",
  ].join(" "),

  dividerTop: ["opacity-60", "blur-[0.3px]"].join(" "),
  dividerScrolled: ["opacity-100", "blur-0"].join(" "),

  hamburgerButton: [
    "flex",
    "items-center",
    "justify-center",
    "w-10",
    "h-10",
    "sm:w-11",
    "sm:h-11",
    "rounded-full",
    "border",
    "border-black/20",
    "hover:border-black/50",
    "hover:bg-black/5",
    "transition-all",
    "duration-300",
    "cursor-pointer",
  ].join(" "),

  hamburgerLine: [
    "block",
    "w-4",
    "sm:w-[18px]",
    "h-[1.5px]",
    "bg-black/60",
    "transition-all",
    "duration-300",
  ].join(" "),
} as const;
