export const navbarStyles = {
  nav: [
    "fixed",
    "top-0",
    "left-0",
    "right-0",
    "z-40",
    "flex",
    "items-center",
    "justify-end",
    "px-6",
    "sm:px-10",
    "lg:px-16",
    "py-4",
    "sm:py-6",
  ].join(" "),

  logo: [
    "text-lg",
    "sm:text-xl",
    "font-light",
    "text-black/80",
    "hover:text-black",
    "transition-colors",
    "duration-300",
    "tracking-tight",
  ].join(" "),

  hamburgerButton: [
    "flex",
    "items-center",
    "justify-center",
    "w-10",
    "h-10",
    "sm:w-11",
    "sm:h-11",
    "rounded-full",
    "border",
    "border-black/20",
    "hover:border-black/50",
    "hover:bg-black/5",
    "transition-all",
    "duration-300",
    "cursor-pointer",
  ].join(" "),

  hamburgerLine: [
    "block",
    "w-4",
    "sm:w-[18px]",
    "h-[1.5px]",
    "bg-black/60",
    "transition-all",
    "duration-300",
  ].join(" "),
} as const;
