export const ordersStyles = {
  wrapper: "relative z-10 flex flex-col items-center justify-start min-h-[calc(100svh-220px)] pt-6 pb-10 px-4",
  container: "w-[calc(100%-1rem)] sm:w-full max-w-[700px] mx-auto my-auto flex flex-col bg-white rounded-[20px] px-6 pt-6 pb-8 sm:px-10 sm:pt-6 sm:pb-8 shadow-sm border border-[#d9d9d9]",
  pageTitle: "text-2xl font-light tracking-tight text-center text-gray-900",
  pageSubtitle: "text-sm font-light my-4 text-center text-black/60",
  emptyState: "w-[calc(100%-1rem)] sm:w-full max-w-[500px] mx-auto my-auto text-center py-12 sm:py-16 px-6 sm:px-10 bg-white shadow-sm border border-[#d9d9d9] rounded-[20px]",
  emptyStateIcon: "mx-auto h-12 w-12 text-gray-400 mb-4",
  emptyStateTitle: "text-lg font-medium text-gray-900",
  emptyStateText: "mt-1 text-sm text-gray-500",
  emptyStateLink: "mt-6 inline-flex items-center rounded-md bg-black px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-800 transition-colors",
  filterContainer: "flex border-b border-gray-100 mt-4 mb-8 w-full justify-around items-center px-2",
  filterButtonBase: "pb-3 px-2 text-[13px] font-semibold transition-all relative cursor-pointer border-b-2 tracking-wider uppercase",
  filterButtonActive: "text-[#111827] border-[#111827]",
  filterButtonInactive: "text-[#6B7280] border-transparent hover:text-gray-900 hover:border-gray-200",
  divider: "border-gray-500 my-6",
  errorState: "text-base text-red-500 text-center py-10 font-light",
};
