export const controlStyles = {
  wrapper: "min-h-screen bg-gray-50 text-black p-2 sm:p-4 md:p-6 font-sans",
  container: "max-w-3xl mx-auto space-y-3 md:space-y-4",
  headerCard: "bg-white p-3 md:p-4 rounded-xl shadow-sm border border-gray-100",
  title: "text-lg md:text-xl font-semibold mb-3 md:mb-4",
  inputGroup: "flex flex-col gap-1.5 mb-3",
  label: "text-[10px] font-bold text-gray-400 uppercase tracking-wider",
  input: "w-full px-3 py-1.5 rounded-lg border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all outline-none text-base bg-gray-50 focus:bg-white",
  grid2: "grid grid-cols-1 md:grid-cols-2 gap-3 md:gap-4",
  
  setCard: "bg-white p-3 md:p-4 rounded-xl shadow-sm border border-gray-100",
  setCardHeader: "text-base font-semibold mb-2 flex justify-between items-center",
  scoreRow: "flex items-center justify-between py-1.5 border-b border-gray-50 last:border-0 gap-3",
  scorePlayerName: "text-base font-medium flex-1 truncate",
  scoreControls: "flex items-center gap-2 md:gap-3",
  scoreBtn: "w-10 h-10 md:w-11 md:h-11 rounded-full flex items-center justify-center text-xl font-medium bg-gray-100 hover:bg-gray-200 active:scale-95 transition-all select-none disabled:opacity-50 disabled:cursor-not-allowed",
  scoreValue: "text-2xl md:text-3xl font-bold w-10 md:w-12 text-center tabular-nums",
  
  winnerGroup: "mt-3 pt-3 border-t border-gray-100",
  winnerTitle: "text-[10px] font-bold text-gray-400 mb-2 text-center uppercase tracking-wider",
  winnerButtons: "flex gap-2",
  winnerBtn: "flex-1 py-1.5 px-3 rounded-lg font-medium transition-all active:scale-95 text-center text-xs md:text-sm",
  winnerBtnActive: "bg-green-500 text-white shadow-md shadow-green-500/20",
  winnerBtnInactive: "bg-gray-100 text-gray-600 hover:bg-gray-200",
  winnerBtnClear: "bg-red-50 text-red-500 hover:bg-red-100",
  
  matchControlCard: "bg-white p-3 md:p-4 rounded-xl shadow-sm border border-gray-100",
  matchWinnerButtons: "flex flex-col sm:flex-row gap-2 mt-3",
  dangerBtn: "w-full mt-4 py-2.5 px-4 rounded-lg font-semibold text-red-600 bg-red-50 hover:bg-red-100 active:scale-95 transition-all text-base border border-red-200",
} as const;
