export const authActionsStyles = {
  wrapper: [
    "mt-2",
    "sm:mt-2",
    "min-h-[88px]",
    "flex",
    "items-center",
    "justify-center",
    "transition-all",
    "duration-1000",
    "ease-out",
  ].join(" "),

  hidden: "opacity-0 translate-y-8",
  visible: "opacity-100 translate-y-0",

  // Sign-in link
  signInLink: [
    "group",
    "flex",
    "items-center",
    "gap-3",
    "text-lg",
    "sm:text-xl",
    "md:text-2xl",
    "lg:text-3xl",
    "font-light",
    "text-black/80",
    "hover:text-black",
    "transition-colors",
    "duration-300",
    "cursor-pointer",
  ].join(" "),

  signInIcon: [
    "flex",
    "items-center",
    "justify-center",
    "w-10",
    "h-10",
    "sm:w-12",
    "sm:h-12",
    "md:w-16",
    "md:h-16",
    "lg:w-20",
    "lg:h-20",
    "rounded-full",
    "border",
    "border-[#5b3fb5]/30",
    "group-hover:border-[#5b3fb5]/60",
    "group-hover:bg-[#5b3fb5]/5",
    "transition-all",
    "duration-300",
    "cursor-pointer",
  ].join(" "),

  signInArrow: [
    "w-4",
    "h-4",
    "sm:w-5",
    "sm:h-5",
    "md:w-7",
    "md:h-7",
    "lg:w-8",
    "lg:h-8",
    "text-[#5b3fb5]",
    "transition-transform",
    "duration-300",
    "group-hover:translate-x-0.5",
  ].join(" "),

  // Logged in text
  loggedInContainer: [
    "flex",
    "flex-col",
    "items-center",
    "justify-center",
    "text-center",
    "gap-3",
    "w-full",
    "max-w-sm",
    "bg-gray-50/80",
    "backdrop-blur-md",
    "border",
    "border-black/10",
    "rounded-xl",
    "p-6",
    "sm:p-8",
    "shadow-sm",
  ].join(" "),

  loggedInText: [
    "text-lg",
    "sm:text-xl",
    "font-light",
    "text-black/80",
  ].join(" "),

  loggedInSubText: [
    "text-sm",
    "font-light",
    "text-black/60",
    "max-w-md",
  ].join(" "),
} as const;
